#define TRACKER_RANK 0
#define MAX_FILES 10
#define MAX_FILENAME 15
#define HASH_SIZE 32
#define MAX_CHUNKS 100
#define ASK_FILE_SIZE 33
#define ASK_FILE_NAME 34
#define ASK_N_HASHES 35
#define ASK_HASHES 36
#define ASK_FILE_NAME_2 13
#define ASK_N_CLIENTS 14
#define TYPE 3
#define ASK_V_CLIENTS 15
#define ASK_N_PRIO 11
#define ASK_V_PRIO 12
#define ASK_FILE_SIZE_3 9
#define ASK_FILE_NAME_3 19
#define ASK_FILE_SIZE_4 7
#define ASK_FILE_NAME_4 27
#define ASK_SEED 17
#define ASK_ACK 8
#define ASK_N_OF_FILES 1
#define ASK_SIZE_DATA 21
#define ASK_HASH_DATA 2
#define ASK_IF_WE_HAVE_THE_DATA 30
#define ASK_N_HASHES_2 31
#define ASK_HASHES_2 32
